---

- name: Create user '{{ item }}'
  user:
    name: "{{ item }}"
    state: present
  register: add_users

# set default_password in the group_vars/all if creating new users
# To create these hashed passwords, run the following command:
#  `openssl passwd -6`
- name: Set default password for '{{ item }}' (when user is new)
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    password: "{{ default_password }}"
  when: add_users.changed

- name: Add user '{{ item }}' to sudoers group
  user:
    name: "{{ item }}"
    state: present
    groups: "{{ 'wheel' if redhat_based else 'sudo' }}"
    append: yes

- name: Ensure SSH path for user '{{ item }}' exists
  file:
    state: directory
    mode: 0700
    path:  "/home/{{ item }}/.ssh"
    owner: "{{ item }}"
    group: "{{ item }}"

- name: Fixing sudo access for user '{{ item }}'
  template:
    dest: "/etc/sudoers.d/{{ item }}"
    src: "sudoers_template.j2"
    mode: 0440
    owner: root
    group: root
    validate: 'visudo -cf %s'

