---
# Installs godoc

- name: check for godoc
  shell:  sudo -u {{ item }} bash -c "source /etc/profile.d/golang.sh; which godoc"
  register: godoc_install
  changed_when: false
  ignore_errors: yes
  args:
    warn: false

- name: install godoc
  shell: sudo -u {{ item }} bash -c "source /etc/profile.d/golang.sh; go get golang.org/x/tools/cmd/godoc"
  when: godoc_install.rc != 0
