---
# Site playbook for dev system, no GUI
- name: common roles for physical and virtual hosts no GUI
  hosts: all
  remote_user: root
  roles:
    - admin_users
    - dev_common
    - golang
    - docker
