---
# Set up roles
- name: role to install user keys
  hosts: all
  vars:
    admin_users: ["{{ my_user }}"]
  remote_user: root

  roles:
    - { role: admin_users, when: my_user != "root" }

  tasks:
  - name: Set user password
    user:
      name: "{{ my_user }}"
      password: "{{ my_password | password_hash('sha512') }}"
      state: present
  - name: Push user rsa pub key to machines
    authorized_key:
      user: "{{ my_user }}"
      state: present
      key: "{{ lookup('file', '/home/{{ my_user }}/.ssh/id_rsa.pub') }}"
    when: my_user != "root" and my_user != "ender"
    ignore_errors: yes
  - name: Push user ed25519 pub key to machines
    authorized_key:
      user: "{{ my_user }}"
      state: present
      key: "{{ lookup('file', '/home/{{ my_user }}/.ssh/id_ed25519.pub') }}"
    when: my_user != "root" and my_user != "ender"
    ignore_errors: yes
