---

# These are just a collection of tools that I've found useful on my desktop that
# happen to be written in rust such that the sure fire way to install them is
# to build them from source.

# This installs packages required for building these specific tools
# Does not install basic rust build requirements, assumes they're already installed
- include_tasks: ubuntu2204.yml
  when: ubuntu2404_based|bool or ubuntu2204_based|bool

# Installing rust tools is actually a per user task
# We're gonna run a loop in a loop
#  main.yml
#    for user in admin_users
#      per_user.yml
#      for app in apps
#        per_app.yml
- include_tasks: per_user.yml
  loop: "{{ admin_users }}"

- include_tasks: per_user.yml
  loop: [root]
