---

- name: Check if '{{ app_name }}' is installed for '{{ current_user }}'
  shell: "source ~/.cargo/env && cargo install --list | grep {{ app_name }}"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ current_user }}"
  register: app_check
  changed_when: false
  ignore_errors: yes

# using --locked because some apps need it.
- name: Install '{{ app_name }}' for '{{ current_user }}'
  shell: "source ~/.cargo/env && cargo install {{ app_name }} --locked --jobs=$(nproc)"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ current_user }}"
  when: app_check.rc != 0
