---
# DESCRIPTION: Set the default Ubuntu ntp and time stuff

- name: "Check the current timezone"
  command: timedatectl show --property=Timezone --value
  register: current_timezone
  changed_when: false

- name: "Ensure the timezone is set to {{ iana_tz }}"
  shell: timedatectl set-timezone {{ iana_tz }}
  when: current_timezone.stdout != iana_tz

#TODO set ntp?