---

- name: Adding udev rules for android
  template:
    src: 51-android.rules.j2
    dest: /etc/udev/rules.d/51-android.rules
  notify: reload udevadm rules

- name: Adding android tools to PATH
  template:
    src: profile.j2
    dest: /etc/profile.d/android.sh
