---
- name: AmazonLinux2 installing epel
  shell: yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: AmazonLinux2 Kernel Build Dependencies Dependencies
  yum:
    name:
      - yum-utils
      - python3
      - python3-pip
      - python3-docutils
      - python3-sphinx
      - hostname
      - openssl
      - asciidoc
      - openssl-devel
      - elfutils-devel
      - binutils-devel
      - newt-devel
      - python-devel
      - "perl(ExtUtils::Embed)"
      - audit-libs-devel
      - numactl-devel
      - pciutils-devel
      - pesign
      - hmaccalc
      - ncurses-devel
      - cpan
      - dpkg
      - dpkg-dev
    state: present

- name: AmazonLinux2 Kernel Build Dependencies
  shell: yumdownloader --source kernel
