---
- name: Debian Kernel Build Dependancies Dependancies
  apt:
    name:
      - libncurses-dev
      - libssl-dev
      - libelf-dev
      - libudev-dev
      - libpci-dev
      - libiberty-dev
      - equivs
      - dwarves
      - dkms
    state: present

- name: Debian Kernel Build Dependancies
  apt:
    name: linux
    state: build-dep
