---
# This installs packages required for building kernel distro packages


- include: ubuntu.yml
  when: ubuntu_based|bool

- include: debian10.yml
  when: "{{ ((ansible_distribution in ['Debian']) and (ansible_distribution_version in ['10'])) }}"

- include: debian.yml
  when: "{{ ((ansible_distribution in ['Debian']) and (ansible_distribution_version not in ['10'])) }}"

- include: redhat.yml
  when: redhat_based|bool

- include: amazonlinux2.yml
  when: amazonlinux2_based|bool

# This is required for the our build scripts
- name: Various python dependancies
  pip:
    name:
      - jinja2
      - GitPython
      - pyaml
