---
# This installs packages required for building kernel distro packages

- include: debian.yml
  when: debian_based|bool

- include: redhat.yml
  when: redhat_based|bool

- include: amazonlinux2.yml
  when: amazonlinux2_based|bool

# This is required for the our build scripts
- name: Various python dependancies
  pip:
    name:
      - jinja2
      - GitPython
      - pyaml
