---
# This installs packages required for QT5 development

- include_tasks: debian.yml
  when: debian_based|bool and not ubuntu_based|bool

- include_tasks: ubuntu2004.yml
  when: ubuntu2004_based|bool

- include_tasks: ubuntu2204.yml
  when: ubuntu2204_based|bool

- include_tasks: redhat.yml
  when: redhat_based|bool

- include_tasks: amazonlinux2.yml
  when: amazonlinux2_based|bool
