---
# This installs packages required for QT5 development

- include: debian.yml
  when: debian_based|bool and not ubuntu_based|bool

- include: ubuntu2004.yml
  when: ubuntu2004_based|bool

- include: ubuntu2204.yml
  when: ubuntu2204_based|bool

- include: redhat.yml
  when: redhat_based|bool

- include: amazonlinux2.yml
  when: amazonlinux2_based|bool
