---
# DESCRIPTION=Copy powerlevel10k config for oh-my-zsh

- name: Copy powerlevel10k config for oh-my-zsh
  hosts: all
  vars_prompt:
    - name: my_user
      prompt: Enter user to update
      unsafe: yes
      private: no
  tasks:
  - name: Get users home directory
    shell: "getent passwd {{ my_user }} | cut -d: -f6"
    register: my_user_home
    changed_when: false
  - name: "Extracting config from local machine"
    local_action:
      module: shell
      cmd: |
        cat {{ my_user_home.stdout }}/.p10k.zsh
    become: no
    changed_when: false
    register: p10k_config
  - name: Write p10k config to machines
    copy:
      content: "{{ p10k_config.stdout }}"
      dest: "{{ my_user_home.stdout }}/.p10k.zsh"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: 664
