---
# DESCRIPTION=Set user unix password

- name: Set user unix password
  hosts: all
  vars_prompt:
    - name: my_user
      prompt: Enter username to update
      unsafe: yes
      private: no
    - name: my_password
      prompt: Enter usernames password
      confirm: yes
      unsafe: yes
      private: yes
  tasks:
  - name: Set user password
    user:
      name: "{{ my_user }}"
      password: "{{ my_password | password_hash('sha512') }}"
      state: present
