---

- name: Debian install KVM
  dnf:
    name: "{{ debian_packages_kvm }}"
    state: present
  become: yes

- name: Debian install vagrant docker script
  copy:
    src: vagrant.docker
    dest: /usr/bin/vagrant
    mode: '0777'
    state: present
