---

- include_tasks: debian.yml
  when: debian_based|bool

- include_tasks: redhat.yml
  when: redhat_based|bool

- include_tasks: vagrant_per_user.yml
  loop: "{{ admin_users }}"

- name: Install vagrant_tools
  get_url:
    url: https://mirror.bitflux.ai/repository/downloads/tools/vagrant_tools
    dest: /usr/bin/vagrant_tools
    mode: 0777
