---

- name: RedHat install KVM
  dnf:
    name: "{{ redhat_packages_kvm }}"
    state: present
  become: yes

- name: RedHat install vagrant podman script
  copy:
    src: vagrant.podman
    dest: /usr/bin/vagrant
    mode: '0777'
