---

- name: Check if hashicorp.gpg exists
  stat:
    path: /etc/apt/trusted.gpg.d/hashicorp.gpg
  register: hashicorp_gpg

- name: Download HashiCorp GPG key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.asc
    mode: '0644'
  when: not hashicorp_gpg.stat.exists

- name: Convert HashiCorp GPG key to binary format
  command: gpg --dearmor /tmp/hashicorp.asc
  args:
    creates: /tmp/hashicorp.gpg
  when: not hashicorp_gpg.stat.exists

- name: Move the binary HashiCorp GPG key to /etc/apt/trusted.gpg.d/
  copy:
    src: /tmp/hashicorp.asc.gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.gpg
    mode: '0644'
  when: not hashicorp_gpg.stat.exists

- name: Clean up temporary HashiCorp GPG files
  file:
    path: /tmp/hashicorp.asc
    state: absent

- name: Add HashiCorp APT repository
  lineinfile:
    path: /etc/apt/sources.list.d/hashicorp.list
    line: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
    state: present
  register: hashicorp_source_list

- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 1
  when: hashicorp_source_list.changed

- name: Install Packer
  apt:
    name: packer
    state: present
