---

- name: Upgrade all packages
  apt:
    upgrade: yes
    force_apt_get: yes
  become: true

# Clean up apt sources wierdness from MAAS stuff
- name: Check if ubuntu.sources exists
  stat:
    path: /etc/apt/sources.list.d/ubuntu.sources
  register: ubuntu_sources

- name: Check if sources.list contains the correct comment
  lineinfile:
    path: /etc/apt/sources.list
    line: '# Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources'
  register: sources_list
  become: true
  when: ubuntu_sources.stat.exists

- name: Ensure sources.list contains only the correct comment if we're doing new style
  shell: echo '# Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources' > /etc/apt/sources.list
  become: true
  when: sources_list.changed

- name: Check if ubuntu-src.sources exists
  shell: |
    cat /etc/apt/sources.list.d/ubuntu.sources | \
    sed 's/Types\: deb$/Types\: deb-src/g' \
    > /etc/apt/sources.list.d/ubuntu-src2.sources;
    AAA=$(diff /etc/apt/sources.list.d/ubuntu-src2.sources /etc/apt/sources.list.d/ubuntu-src.sources 2>&1);
    rm /etc/apt/sources.list.d/ubuntu-src2.sources
    if [ ! -z "$AAA" ]; then
      exit 1
    fi
  changed_when: false
  register: ubuntu_src_sources

- name: Check if ubuntu-src.sources contains the correct data
  shell: |
    cat /etc/apt/sources.list.d/ubuntu.sources | \
    sed 's/Types\: deb$/Types\: deb-src/g' \
    > /etc/apt/sources.list.d/ubuntu-src.sources
  register: ubuntu_src_updated
  when: ubuntu_src_sources.rc  != 0

- name: Update apt package cache again
  apt:
    update_cache: yes
    cache_valid_time: 1
  become: true
  when: ubuntu_src_updated.changed
