---
# Sets up tigervnc

- name: tigervnc_debian
  include_tasks: debian.yml
  when: debian_based|bool

- name: tigervnc_redhat
  include_tasks: redhat.yml
  when: redhat_based|bool

- include_tasks: per_user.yml
  loop: "{{ vnc_users }}"
  loop_control:
    index_var: index
