---
- name: Debian Install python
  apt:
    name: [ python-apt, python3-apt, python3-pip ]
    state: present

- name: Debian Common development tools
  apt:
    name:
      - build-essential
      - cmake
      - git
      - rsync
      - gcc
      - gnupg
      - rpm
      - cppcheck
      - autoconf
      - asciidoc
      - bc
      - cpio
      - bison
      - flex
      - gawk
      - gettext
      - gzip
      - hostname
      - m4
      - net-tools
      - openssl
      - xmlto
      - zstd
    state: present
