---
# This installs development tools
- include_tasks: debian.yml
  when: debian_based|bool

- include_tasks: redhat.yml
  when: redhat_based|bool

- include_tasks: amazonlinux2.yml
  when: amazonlinux2_based|bool

- name: Various python dependancies
  pip:
    name:
      - jinja2
      - GitPython
      - pyaml
  when: not ubuntu2404_based|bool
