---
# This installs common base of packages for desktop / workstation machines

- include: debian.yml
  when: debian_based|bool

- include: redhat.yml
  when: redhat_based|bool

- name: Stop auto scanning for printers, it was really annoying
  systemd:
    name: cups-browsed
    enabled: false
    state: stopped
  ignore_errors: yes

- name: Various python dependancies
  pip:
    name:
      - jinja2
      - GitPython
      - pyaml
