---
# This installs development tools

- name: Print some debug information 
  vars: 
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info

- include: debian.yml
  when: debian_based|bool

- include: redhat.yml
  when: redhat_based|bool

- name: Various python dependancies
  pip:
    name:
      - jinja2
      - GitPython
      - pyaml
