---
# This installs development tools

- include: debian.yml
  when: debian_based|bool

- include: redhat.yml
  when: redhat_based|bool

- name: Various python dependancies
  pip:
    name:
      - jinja2
      - GitPython
      - pyaml
