---
###############################################################################
#  These tasks are idempotent versions of the instructions
#
#  https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
#
###############################################################################

- name: Install nvidia container toolkit keyring
  shell: |
    rm -f /tmp/new-nvidia-container-toolkit-keyring.gpg && \
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /tmp/new-nvidia-container-toolkit-keyring.gpg && \
    if [ ! -f /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg ]; then \
      NCT_DIFF="greenfield"; \
    fi && \
    if [ "$NCT_DIFF" ]; then \
      curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg; \
      echo "changed"; \
    fi
  register: nct_keyring_check
  changed_when: nct_keyring_check.stdout == "changed"

- name: Install nvidia container toolkit sources list
  shell: |
    NEW_NCT_SOURCES_LIST=$(curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g') && \
    if [ -f /etc/apt/sources.list.d/nvidia-container-toolkit.list ]; then \
      OLD_NCT_SOURCES_LIST=$(cat /etc/apt/sources.list.d/nvidia-container-toolkit.list); \
    fi && \
    if [ "$NEW_NCT_SOURCES_LIST" != "$OLD_NCT_SOURCES_LIST" ]; then \
      echo "$NEW_NCT_SOURCES_LIST" > /etc/apt/sources.list.d/nvidia-container-toolkit.list;
      echo "changed"; \
    fi
  register: nct_sources_list_check
  changed_when: nct_sources_list_check.stdout == "changed"

- name: Install nvidia container toolkit binaries
  apt:
    name: "{{ nvidia_container_toolkit_packages }}"
    update_cache: yes
    state: present
  notify: restart docker daemon
