---
- name: Debian common dependencies
  apt:
    state: present
    name:
      - wget
      - acpid
      - firewalld
      - cockpit
      - cockpit-pcp
      - cockpit-machines

- name: Enable and start cockpit
  systemd:
    name: cockpit
    state: started
    enabled: yes
  notify: force enable now cockpit
