---

- name: Install epel-release as it's own step to avoid issues.
  dnf:
    state: present
    name: epel-release

- name: Install common dependencies, beyond epel...
  dnf:
    state: present
    name:
      - wget
      - curl
      - acpid
      - firewalld
      - cockpit
      - cockpit-pcp
      - cockpit-machines
      - podman

- name: Enable and start cockpit
  systemd:
    name: cockpit
    enabled: yes
  # this line is not idempotent, what is above is, if we need a restart for a config change
  # that should be done with a handler.
  # notify: force enable now cockpit
