---

- name: Check for existing filesystems on device {{ item.devices }}
  command: lsblk -f --noheadings --output FSTYPE {{ item.devices | join(' ')  }}
  failed_when: false
  changed_when: false
  register: disk_check

- name: Create Btrfs filesystem {{ item.mount_point }}
  command: >
    mkfs.btrfs {{ item.format_options }} {{ item.devices | join(' ') }}
  args:
    creates: "{{ item.mount_point }}"

- name: Create mount point {{ item.mount_point }}
  file:
    path: "{{ item.mount_point }}"
    state: directory

- name: Add to /etc/fstab {{ item.mount_point }}
  lineinfile:
    path: /etc/fstab
    line: "{{ item.devices[0] }} {{ item.mount_point }} btrfs defaults 0 0"
    state: present
  register: add_to_fstab

- name: Mount all filesystems
  command: mount -a
  when: add_to_fstab.changed

- name: Set permissions for mount point {{ item.mount_point }}
  file:
    path: "{{ item.mount_point }}"
    state: directory
    mode: '0777'
