#####################################################################################################
#
#   These versions should be updated as needed.
#
#####################################################################################################

cuda_keyring_version: "1.1-1"
cuda_keyring_repo: >-
  {% if ubuntu2404_based %}
  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
  {% elif ubuntu2204_based %}
  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
  {% endif %}

cuda_repo_list: >-
  {% if ubuntu2404_based %}
  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/
  {% elif ubuntu2204_based %}
  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/
  {% endif %}


nvidia_driver_packages:
  - nvidia-driver-575
  - nvidia-dkms-575
  - cuda-drivers-575

cuda_packages:
  - cuda-toolkit-12-9
  - cuda-tools-12-9
  - cuda-compiler-12-9
  - cuda-libraries-12-9
  - cuda-libraries-dev-12-9
  - libcudnn9-cuda-12
  - libcudnn9-dev-cuda-12
  - libcudnn9-headers-cuda-12
  - nvidia-gds-12-9
  - nvtop

cuda_install_path: /usr/local/cuda-12.9

nvidia_container_toolkit_packages:
  - nvidia-container-toolkit=1.17.8-1
  - nvidia-container-toolkit-base=1.17.8-1
  - libnvidia-container-tools=1.17.8-1
  - libnvidia-container1=1.17.8-1
