---
# For APT based distros that use /etc/apt/sources.list, older version mostly

- name: Turn on source repos to /etc/apt/sources.list
  shell: |
    cp /etc/apt/sources.list /etc/apt/sources.list.ansible
    if [ -z "$( cat /etc/apt/source.list.ansible | grep deb-src )" ]; then
      sed -Ei 's/^deb /deb-src /' /etc/apt/sources.list.ansible-src
      cat /etc/apt/sources.list.ansible-src | grep deb-src >> /etc/apt/sources.list.ansible
      rm /etc/apt/sources.list.ansible-src
    else
      # Some distros have src repos commented out
      sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list.ansible
    fi
    if [ -z "$(diff /etc/apt/sources.list /etc/apt/sources.list.ansible)" ]; then
      rm /etc/apt/sources.list.ansible
      echo "NO_CHANGE_TO_SOURCES_LIST"
    fi
    mv /etc/apt/sources.list.ansible /etc/apt/sources.list
  register: shell_output
  changed_when: "NO_CHANGE_TO_SOURCES_LIST in shell_output.stdout"
