---
# For APT based distros that use /etc/apt/sources.list.d/

- name: Create ubuntu-src.sources
  shell: |
    cat /etc/apt/sources.list.d/ubuntu.sources | \
    sed 's/Types\: deb$/Types\: deb-src/g' \
    > /etc/apt/sources.list.d/ubuntu-src2.sources;
    AAA=$(diff /etc/apt/sources.list.d/ubuntu-src2.sources /etc/apt/sources.list.d/ubuntu-src.sources 2>&1);
    if [ ! -z "$AAA" ]; then
      mv /etc/apt/sources.list.d/ubuntu-src2.sources /etc/apt/sources.list.d/ubuntu-src.sources
      echo UBUNTU_SOURCES_MISSING
    else
      rm /etc/apt/sources.list.d/ubuntu-src2.sources
    fi
  register: ubuntu_src_sources
  changed_when: "'UBUNTU_SOURCES_MISSING' in ubuntu_src_sources.stdout"

- name: Update apt package cache again
  apt:
    update_cache: yes
    cache_valid_time: 1
  become: true
  when: ubuntu_src_sources.changed
