---

# We need the users prefered shell to tell if cargo is installed
- name: Get default shell for '{{ item }}'
  command: getent passwd {{ item }}
  register: passwd_info
  changed_when: false

- name: Parse default shell for '{{ item }}'
  set_fact:
    user_shell: "{{ passwd_info.stdout.split(':')[-1] | trim }}"

- name: Check if cargo is installed for '{{ item }}' who uses '{{ user_shell }}'"
  shell: |
    {{ user_shell }} -lc 'which cargo'
  become: yes
  become_user: "{{ item }}"
  register: cargo_check
  changed_when: false
  ignore_errors: yes

- name: Download rustup script
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755
  when: cargo_check.rc != 0

# Install rust
- name: Install rust and tools with the rustup script for '{{ item }}'
  command: /tmp/rustup.sh -y
  become: yes
  become_user: "{{ item }}"
  when: cargo_check.rc != 0


# Install cargo-deb
- name: Check if cargo-deb is installed for '{{ item }}'
  shell: |
    {{ user_shell }} -lc 'which cargo-deb'
  become: yes
  become_user: "{{ item }}"
  register: cargodeb_check
  changed_when: false
  ignore_errors: yes

- name: Install cargo-deb
  shell: . ~/.cargo/env && cargo install cargo-deb
  become: yes
  become_user: "{{ item }}"
  when: cargodeb_check.rc != 0


# Install cargo-generate-rpm
- name: Check if cargo-generate-rpm is installed for '{{ item }}'
  shell: |
    {{ user_shell }} -lc 'which cargo-generate-rpm'
  become: yes
  become_user: "{{ item }}"
  register: cargorpm_check
  changed_when: false
  ignore_errors: yes

- name: Install cargo-generate-rpm
  shell: . ~/.cargo/env && cargo install cargo-generate-rpm
  become: yes
  become_user: "{{ item }}"
  when: cargorpm_check.rc != 0

- name: Install cargo-generate-rpm
  shell: . ~/.cargo/env && cargo install cargo-generate-rpm
  become: yes
  become_user: "{{ item }}"
  when: cargorpm_check.rc != 0

- name: Check if x86_64-unknown-linux-musl is installed for '{{ item }}'
  shell: . ~/.cargo/env && rustup target list | grep x86_64-unknown-linux-musl | grep installed
  become: yes
  become_user: "{{ item }}"
  register: musl_check
  changed_when: false
  ignore_errors: yes

- name: Install rustup target x86_64-unknown-linux-musl for '{{ item }}'
  shell: . ~/.cargo/env && rustup target add x86_64-unknown-linux-musl
  become: yes
  become_user: "{{ item }}"
  when: musl_check.rc != 0
