---
- name: Ubuntu2204 tensorflow build Dependancies
  apt:
    name:
      - libstdc++-12-dev
    state: present

- name: Download rustup script
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755

- name: Run rustup script
  command: /tmp/rustup.sh -y

- name: Install cargo-deb
  command: cargo install cargo-deb

- name: Install cargo-generate-rpm
  command: cargo install cargo-generate-rpm
