# Installs docker

- name: Override ansible_distribution for Rocky compatibility
  set_fact: ansible_distribution='RedHat'
  when: redhat_based|bool

- name: Override ansible_os_family for Rocky compatibility
  set_fact: ansible_os_family='RedHat'
  when: redhat_based|bool

- name: RedHat has podman installed, probably could work but lets install docker
  dnf:
    name:
      - podman
      - runc
    state: absent
  when: redhat_based|bool

- name: docker install
  include_role:
    name: geerlingguy.docker
