---

# DESCRIPTION=Helps debug how Ansible is running
- name: Helps debug how Ansible is running
  hosts: all
  remote_user: root
  vars: 
    msg: |
        ansible_distribution: {{ ansible_distribution }}
        ansible_distribution_version: {{ ansible_distribution_version }}
  tasks:
  - name: Print out ansible variables
    debug: 
      msg: "{{ msg.split('\n') }}"       
