---

- name: Deploy Influx dnf/yum repo
  template:
    src: influxdb-repo.j2
    dest: /etc/yum.repos.d/influxdb.repo

- name: RedHat Install Telegraf
  dnf:
    state: present
    name: [ telegraf ]
